# Generated by Django 4.2.2 on 2023-07-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_proocional',
            new_name='preco_promocional',
        ),
    ]
